config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :plays
  root 'plays#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/play.rb
class Play < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :find_play, only: [:show,:edit,:update,:destroy]

  def index
    @plays = Play.all.order('created_at DESC')
  end

  def new
    @play = current_user.play.build
  end

  def create
    @play = current_user.play.build(play_params)
    if @play.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit

  end

  def update
    if @play.update(play_params)
      redirect_to play_path
    else
      render 'edit'
    end
  end

  def destroy
    @play.destroy
    redirect_to root_path
  end

  private

  def play_params
    params.require(:play).permit(:title,:description,:director)
  end

  def find_play
    @play = Play.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Broadwayy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Broadway", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "Add Play", new_play_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/plays/_form.html.erb
<%= simple_form_for @play do |f| %>
    <%= f.input :title, label:  "Play Title" %>
    <%= f.input :description %>
    <%= f.input :director %>
    <%= f.button :submit %>
<% end %>

app/views/plays/edit.html.erb
<h1>Edit Broadway Play</h1>
<%= render 'form' %>

app/views/plays/index.html.erb
<% @plays.each do |play| %>
  <h2><%= link_to play.title, play_path(play) %></h2>
<% end %>

app/views/plays/new.html.erb
<h1>New Broadway Play</h1>
<%= render 'form' %>

app/views/plays/show.html.erb
<h2><%= @play.title %></h2>
<h3><%= @play.director %></h3>
<p><%= @play.description %></p>
<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_play_path(@play) %>
<%= link_to "Delete", play_path(@play), method: :delete, data: {confirm: "Are you sure?"} %>